name = "Main"
license = "MIT"
licenselink = "https://github.com/popskraft/nutcracker/blob/main/LICENSE"
description = "Custom theme for Nutcracker Products website"
homepage = "https://github.com/popskraft/nutcracker"
tags = ["product", "business", "responsive"]
features = ["responsive", "fast"]
min_version = "0.140.2"

[author]
  name = "Alex Pop"
  homepage = "https://github.com/popskraft"
